Added basic methods for DownloadStation.API
plneto/Synology.Api.Client pull request #15
Opened 2023-03-08 06:57 UTC by ikocs

We propose the implementation of the following methods:

- Info:
  - Info;
  - SetServerConfig;
  - GetConfig;
- Task
  - Create (due to bugs in Synology, it is only possible to add from the link);
  - Delete;
  - Pause;
  - Resume.

2023-03-08 11:43 UTC, plneto commented
Thanks for submitting this PR. I'll try to review it soon.

I noticed that you added some PDFs to the repository which I think are the same ones that are already in the `docs` folder. Can you please check and remove them if they are duplicates?

2023-03-08 15:21 UTC, ikocs commented
> Thanks for submitting this PR. I'll try to review it soon.
> 
> I noticed that you added some PDFs to the repository which I think are the same ones that are already in the `docs` folder. Can you please check and remove them if they are duplicates?

fix it

2023-03-12 06:24 UTC, PeskovV commented
`ISynologyHttpClient` has `GetAsync` method with `queryParams`. It had type `Dictionary<string, string>`
I made `Dictionary<string, string?>` because some parameters are optional

2023-07-20 11:02 UTC, plneto commented on src/Synology.Api.Client.Integration.Tests/DownloadStationApiTests.cs
> +            var delRequest = new DownloadStationTaskDeleteRequest
Did you forget to execute the delete request?

2023-07-20 11:05 UTC, plneto commented on src/Synology.Api.Client/Apis/DownloadStation/Info/IDownloadStationInfoEndpoint.cs
> +        Task<DownloadStationServerConfig> GetConfigAsync();
Can you please add the XML documentation to these 2 methods as well?

2023-07-20 11:07 UTC, plneto commented on src/Synology.Api.Client/Apis/DownloadStation/Info/Models/DownloadStationServerConfig.cs
> +        public DownloadStationServerConfig(
What's the expected behaviour when you set only one config and all the other values are null? Are the ones with null values ignored by the DSM?

2023-07-20 11:22 UTC, plneto commented on src/Synology.Api.Client/SynologyHttpClient.cs
> +                        if (!response?.Success ?? true)
Maybe we change this line to make it easier to understand? Something like `if (!(response?.Success ?? false))`

2023-07-20 11:24 UTC, plneto requested changes
Looks good to me. Please fix the minor issues from the comments I left.

2023-07-22 09:23 UTC, ikocs commented
Good afternoon In the near future there will be no time at all to look at and correct the comments. But I hope to return to the project soon.

2023-07-22 13:03 UTC, plneto commented
> Good afternoon In the near future there will be no time at all to look at and correct the comments. But I hope to return to the project soon.

No worries, I'll merge the PR. They are minor issues so you can fix them later.

2023-07-22 13:03 UTC, merged